using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//Enemy Controller
//Julian Escobar Echeverri
//StudentID: 101286557
//last modified: 2021-10-18
//description: Controller for the enemy.
//History:
//2021-10-18: change behaviour from portrait to landscape.
//


public class EnemyController : MonoBehaviour
{
    public float verticalSpeed;
    public float verticalBoundary;
    public float direction;

    // Update is called once per frame
    void Update()
    {
        _Move();
        _CheckBounds();
    }

    private void _Move()
    {
        transform.position += new Vector3(0.0f, verticalSpeed * direction * Time.deltaTime, 0.0f);
    }

    private void _CheckBounds()
    {
        // check right boundary
        if (transform.position.y >= verticalBoundary)
        {
            direction = -1.0f;
        }

        // check left boundary
        if (transform.position.y <= -verticalBoundary)
        {
            direction = 1.0f;
        }
    }
}
